### PR TITLE
Fixed saving issue

### PR DESCRIPTION
**Pull request by ducitymp**
This fixed the save issue

### CODE REVIEW

**Comment by mibby** [comment]
@drtshock Any chances on getting this merged? ^^

**Comment by drtshock** [comment]
The problem is I'm worried this will break having multiple people view a vault at the same time since it doesn't check to make sure there's only one viewer.

**Comment by ducitymp** [comment]
@drtshock I can fix that and do another pull request.

**Comment by drtshock** [comment]
Please include it in this one. I don't want one pull requested needed to fix another to be pulled ;)

**Comment by drtshock** [comment]
And thank you a ton for helping out! I really appreciate it.

**Comment by ducitymp** [comment]
@drtshock Updated and I'm happy that i can help!

**Comment by drtshock** [comment]
Formatting? And can you explain what you did and why please

**Comment by ducitymp** [comment]
I added a check so it saves when there is only one player viewing the inventory and i used inventory instead of inv so it check for the inventory not the copied one that i made earlier to prevent dup glitches.

**Comment by drtshock** [comment]
Yeah it looks like the issue was just that it was checking the wrong inventory.

**Pull request merged**
