### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by ZiluckMichael**

### CODE REVIEW

**Comment by kashike** [comment]
Why?

**Comment by ZiluckMichael** [comment]
There is a problem with older versions (specifically those before 1.5) of the maven shade plugin that causes creating the shaded jar to fail.

The error message is similar to the one found here: https://issues.apache.org/jira/browse/MSHADE-99

The solution I found is located here: https://bukkit.org/threads/building-craftbukkit-with-maven.231990/, although I also found that exact same suggestion elsewhere and was one of the 

I am unsure if you will be able to replicate the problem I had with compiling the project, but this solution does not have any adverse effects elsewhere and could fix the problem for someone who might have it in the future.

**Comment by ZiluckMichael** [comment]
Additional side note, the version of the shade plugin used in drtshock's factions is 2.4.3. Version 1.4 is incredibly old and isn't being supported.

**Comment by kashike** [comment]
Thanks for the explanation.

**Pull request merged**
