### PR TITLE
Delete all vaults (1-100)

### LINKED ISSUE #352: Issue with pvdel, and potential solution.
**PlayerVaultsX version:**
Compiled as of:
https://github.com/drtshock/PlayerVaults/commit/3bd3368f4df6cbd38571c3cfd93d67b07a9bac88
(Purchase and payment has been made via Spigot of course) :)

**Server software:**
Spigot-B1545

**Server:**
Details on request.

**Details:**
So I am having a bit of a problem with ASkyBlock and PlayerVaults. I'll be as to the point as possible.
ASkyBlock has the following config:

resetcommands:
    - "pvdel [player] 1"
    - "pvdel [player] 2"
    - "pvdel [player] 3"
    - "pvdel [player] 4"
    - "pvdel [player] 5"

Our players get 5 vaults.
Basically when a player resets island, above commands are run.

Console example during above process: https://i.imgur.com/ypMSH9j.png

**Issue:**
It seems ASkyBlock is running all these commands at the same time immediately via console. There is no timeout or anything between commands. I have tested other plugins, and I do not experience any issue with throwing multiples of their commands and having them run immediately, however, with PlayerVaults it seems running all 5 at the same time, causes the vaults to not be cleared.

I have tested running one pvpdel player commands, works!
I have tested running two pvpdel player commands, works!
I have tested running three pvpdel player commands, 50% change of working.
I have tested running four pvpdel player commands, 10% change of working.
* In fact sometimes it just clears the first vault, and not 2, 3, or 4.
I have tested running five pvpdel player commands, 0% change of working.
(I'm basing my % on the amount of tests I've done in my environment).

**Solutions:**
- Figure out what's going on and fix? (Lmao easier said than done)
- **highly preferred** Simply provide us with a "pvpdel player all" or "pvpdel player" or "pvpclear player" or other of your choice command to allow clearing an entire players vaults file with a single command via console.

I am available for testing should you need updates on the ticket.
Just tag me and I'll compile and get on that :)

### PR DESCRIPTION
**Pull request by JamieSinn**
Resolves #352

### CODE REVIEW

**Comment by drtshock** [comment]
This is a workaround for that, not a proper solution to vaults not deleting correctly.

That being said, I agree that this should be a feature. I want to look into the vault management to make sure there isn't a better way to do this. Thank you for your contribution though! I will either pull as is, or pull with minor changes in the next few days.

**Comment by JamieSinn** [comment]
I agree it's not a proper feature, but there's currently no way to get all the vaults that a player has, and that's something requiring blocking File IO, which I'd rather do without.

Feel free to make changes as you see fit.

**Comment by JamieSinn** [comment]
Any status update? @drtshock

**Comment by drtshock** [comment]
Merged with a small change.

**Pull request closed without merging**
